import Head from 'next/head';
import { useState } from 'react';
import Form from '../components/form/Form';
import Paragraphs from '../components/paragraphs/Paragraphs';

import textData from '../data/data';

export default function Home() {
  const [textList, setTextList] = useState(textData);
  const [displayedParagraphs, setDisplayedParagraphs] = useState(0);

  return (
    <>
      <Head>
        <title>Lorem Ipsum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form setDisplayedParagraphs={setDisplayedParagraphs} />
      <Paragraphs
        textList={textList}
        displayedParagraphs={displayedParagraphs}
      />
    </>
  );
}
